# Here you can specify default options for TinyMCE across all controllers
#
# theme: advanced
# plugins:
#  - table
#  - fullscreen
# //   script_url : '/javascripts/tinymce/tiny_mce.js',
# //   theme : "advanced",
# //   plugins : "pdw,pagebreak,style,layer,table,save,advhr,advimage,advlink,emotions,iespell,inlinepopups,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template,advlist",
# //   theme_advanced_buttons1 : "pdw_toggle,bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,formatselect,cut,copy,paste,pastetext,pasteword",
# //   theme_advanced_buttons2 : "search,replace,|,bullist,numlist,|,outdent,indent,blockquote,|,undo,redo,|,link,unlink,anchor,image,cleanup,help,code,preview",
# //   theme_advanced_buttons3 : "tablecontrols,|,hr,removeformat,visualaid,|,sub,sup,|,media,|,fullscreen",
# //   theme_advanced_toolbar_location : "top",
# //   theme_advanced_toolbar_align : "left",
# //   theme_advanced_statusbar_location : "bottom",
# //   theme_advanced_resizing : true,
# //   theme_advanced_resize_horizontal : false,
# //   pdw_toggle_on : 1,
# //   pdw_toggle_toolbars : "2,3",
# //   content_css : "/stylesheets/tinymce/custom_html_editor.css"
# // });

theme: advanced
content_css: /stylesheets/tinymce/custom_rich_editor.css
theme_advanced_toolbar_location: top
theme_advanced_toolbar_align: left
theme_advanced_statusbar_location: bottom
theme_advanced_resizing: true
theme_advanced_resize_horizontal: false
theme_advanced_buttons1:
- bold
- italic
- underline
- strikethrough
- |
- justifyleft
- justifycenter
- justifyright
- justifyfull
- styleselect
- formatselect
- cut
- copy
- paste
- pastetext
- pasteword
theme_advanced_buttons2:
- search
- replace
- |
- bullist
- numlist
- |
- outdent
- indent
- blockquote
- |
- undo
- redo
- |
- link
- unlink
- anchor
- image
- cleanup
- help
- code
- preview
theme_advanced_buttons3:
- tablecontrols
- |
- removeformat
- visualaid
- |
- sub
- sup
- |
- media
- |
- fullscreen
extended_valid_elements: "iframe[src|width|height|name|align]"
plugins:
- paste
- pagebreak
- style
- layer
- table
- save
- advhr
- advimage
- advlink
- emotions
- iespell
- inlinepopups
- insertdatetime
- preview
- media
- searchreplace
- print
- contextmenu
- paste
- directionality
- fullscreen
- noneditable
- visualchars
- nonbreaking
- xhtmlxtras
- template
- advlist